### PR TITLE
No hardcoded ruby path, debug message for checksum script upload

### PR DESCRIPTION
**Pull request by ytsarev**
- Ability to configure remote ruby path
- Debug message during checksum script upload

### CODE REVIEW

**Comment by ytsarev** [comment]
@coderanger any feedback ?

**Comment by ytsarev** [comment]
@coderanger it's been a while, could you take  a look ?

**Comment by coderanger** [comment]
What's the use case?

**Comment by ytsarev** [comment]
using this gem on systems without ChefSDK

**Comment by coderanger** [comment]
Do you mean for things like testing with Puppet? Because this isn't related to ChefDK, that Ruby is from the standard chef-client packages which are required for Chef testing.

**Comment by ytsarev** [comment]
@coderanger exactly, my use case is puppet testing and i just need to use system ruby interpreter

**Comment by coderanger** [comment]
Okay, there are a few open issues around non-Chef use cases. I want to get a better idea of how those should play out before I move forward.

**Comment by ytsarev** [comment]
@coderanger it's been a while.. do you want to proceed with that one ?

**Comment by coderanger** [comment]
It's on my list to circle back to eventually.

**Comment by fiunchinho** [comment]
any news on this PR?

**Comment by ytsarev** [comment]
Nice argumentation as always.

**Pull request closed without merging**
